### ISSUE TITLE
Ganztägige Events

### ISSUE THREAD

**Issue by saerdnaer** [muccc/wiki_kalenderscraper#2]
Events die im Kalender ohne Uhrzeit sehen sollten als ganztägige Events im Kalender landen.
Sofern ein Event mehrere Tage dauert, sollte dies mehreren Zeilen im wiki auch zusammengezogen werden. Hatten wir letzteren Fall eigentlich bisher schon?

**Comment by saerdnaer** [comment]
@chris007de Wie ist der aktuelle Stand?

**Comment by chris007de** [comment]
@saerdnaer Hab mal was eingebaut...wenn ein Termin keine Uhrzeit eingetragen hat, wirds automatisch als ganztags-Event angesehen. Ueber das korrekte Format scheiden sich die Geister (https://stackoverflow.com/questions/1716237/single-day-all-day-appointments-in-ics-files), das verwendete funktioniert zumindest in Lightning.

**Comment by saerdnaer** [comment]
Bei mir funktioniert's in der OS X iCal App soweit auch. Einziger Kritikpunkt wäre noch mehrtägige Events: 
<img width="643" alt="temp" src="https://cloud.githubusercontent.com/assets/40266/13899793/22a6d51c-edf7-11e5-85f7-5d068e7e1430.png">

Die gelben Events kommen aus dem Feed, das grüne ist ein lokaler Eintrag. Ich frage mich grade ob man die drei einzelnen Events am besten im Python-Code auf Basis des Namens merged oder ob wir das im Wiki anders eintragen sollen.

**Comment by derchrisuk** [comment]
Ich habe gerade mal was gepushed: 36301bb3ecf0998a16980cca8fca1ddaac973f6e
Bei meinen Test war es ok.
Wenn ein Event keine Zeit hat, und der Name des Events gleich ist, wird es zusammengefasst.
Es bleibt der 1. Eintrag ueberig, und der bekommt noch die Anzahl der Tage wie lange das Event dauert.
Daraus wird dann ein Eintrag im .ics mit X Länge.

**Comment by saerdnaer** [comment]
Ich habs mal deployed. Sieht gut aus. :+1:
