### ISSUE TITLE
Einträge haben keine UIDs

### ISSUE THREAD

**Issue by pc-coholic** [muccc/wiki_kalenderscraper#3]
Anscheinend mögen einige Kalender-Applikationen (Khal?) das nicht, wenn die einzelnen Events keine UID haben.

**Comment by robinkaranu** [comment]
Hups - hab ganz übersehen das du ein Ticket aufgemacht hast. Habs (ziemlich dreckig und auch nicht so viel standardnäher) eingebaut: https://github.com/muccc/wiki_kalenderscraper/commit/c591e92f181b826a9cfafd69ca6de499d6b364b3

muss das wer deployen?

**Comment by saerdnaer** [comment]
@fpletz kannst du das mal deployen

**Comment by saerdnaer** [comment]
Laut Fpletz ist das schon deployed.
