### ISSUE TITLE
UID ist nicht eindeutig

### ISSUE THREAD

**Issue by saerdnaer** [muccc/wiki_kalenderscraper#4]
Anbei mal ein Auszug von aus dem ical File von heute:
```
BEGIN:VEVENT
SUMMARY:SSDeV
DTSTART;VALUE=DATE-TIME:20151211T193000
DTEND;VALUE=DATE-TIME:20151211T213000
UID:wikical16.12.Congress-Vorbereitungstreffen20.00@api.muc.ccc.de
END:VEVENT
BEGIN:VEVENT
SUMMARY:Freifunk Weihnachts Funk-Up
DTSTART;VALUE=DATE-TIME:20151214T200000
DTEND;VALUE=DATE-TIME:20151214T220000
UID:wikical16.12.Congress-Vorbereitungstreffen20.00@api.muc.ccc.de
END:VEVENT
BEGIN:VEVENT
SUMMARY:Vortrag: Smart Space UI
DTSTART;VALUE=DATE-TIME:20151215T201500
DTEND;VALUE=DATE-TIME:20151215T221500
UID:wikical16.12.Congress-Vorbereitungstreffen20.00@api.muc.ccc.de
END:VEVENT
BEGIN:VEVENT
SUMMARY:Congress-Vorbereitungstreffen
DTSTART;VALUE=DATE-TIME:20151216T200000
DTEND;VALUE=DATE-TIME:20151216T220000
UID:wikical16.12.Congress-Vorbereitungstreffen20.00@api.muc.ccc.de
END:VEVENT
```
Die UID ist bei allen Einträgen die selbe. Das sorgt bei meinem Kalender dafür, das nur ein Termin angezeigt wird. Hier im Repo ist der Bug anscheinend schon gefixed (vgl. https://github.com/muccc/wiki_kalenderscraper/commit/e61c4223ffa490948bba03f09763f591c4bf63ad) , aber auf uberbus liegt in /home/fpletz/wiki_kalenderscraper anscheinend noch ne alte Version...

@fpletz Hat das irgendeinen bestimmen Grund? Kannst du die mal aktualisieren?

**Comment by fpletz** [comment]
Weil niemand was gesagt hat? Done.

**Comment by saerdnaer** [comment]
Thx!
