### ISSUE TITLE
Zeitzone setzen

### ISSUE THREAD

**Issue by Sec42** [muccc/wiki_kalenderscraper#8]
Das generierte .ics enhält keine Zeitzoneninformation. "ics Droid" wird dadurch verwirrt und importiert die Termine mit der Zeitzone "Bissau".

Habe q&d getestet, das .icd schnell wie folgt modifiziert:

< cal.ics perl -ple 's!^(DTSTART|DTEND);(.*)!$1;TZID=Europe/Berlin;$2!'  > newcal.ics

Das Resultat importiert fehlerfrei und mit korrekter Zeitzone.

**Comment by derchrisuk** [comment]
Ich hatte da schonmal reingeschaut.
In dem Python Modul muss nur die TZ gesetzt werden für jeden DTSTART/END

`tzinfo=pytz.timezone("Europe/Berlin")`

Allerdings erstellen wir das DTSTART/END sehr umstaendlich, so das ich da noch nicht erkennen konnte wie man das dort am besten integriert.

**Comment by saerdnaer** [comment]
@Sec42 Gerüchteweise hast du dafür schon einen Fix erstellt, kannst du daraus einen PR machen?

**Comment by Sec42** [comment]
Das Gerücht ist entweder falsch, oder ich kann mich nicht mehr daran erinnern. In meinem lokalen git sind keine Änderungen zu dem Thema zu finden.

Sorry.

**Comment by git-commit** [comment]
Fix dafür ist jetzt als PR #13 verfügbar.
